clasedjango/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',  include('polls.urls'))
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:question_id>/', views.detail, name="Detalle"),
    path('<int:question_id>/results/', views.results, name="Resultados"),
    path('<int:question_id>/vote/', views.vote, name="votar"),
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choise(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choise_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choise_text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from django.template import loader

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/show.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

polls/templates/polls/index.html
<table border="3">
    <thead>
        <tr>
            <th>Question Text</th>
        </tr>
    </thead>
    <tbody>
        {% for question in latest_question_list %}
            <tr>
                <td><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></td>
            </tr>
    {% endfor %}
    </tbody>
</table

polls/templates/polls/show.html
<h1>Pregunta</h1>
<p>Text: {{ question }}

<h2>Opciones</h2>
<table border="3">
    <thead>
        <tr>
            <th>Choise Text</th>
            <th>Vote</th>
        </tr>
    </thead>
    <tbody>
        {% for choise in question.choise_set.all %}
            <tr>
                <td>{{ choise.choise_text }}</td>
                <td>{{ choise.vote }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table

<br>
<a href="/polls/">Volver a la lista</a>